apiVersion: v1
kind: Service
metadata:
  name: mynt-frontend
  namespace: default
  labels:
    app: mynt-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: mynt-frontend
